kind: PersistentVolumeClaim
apiVersion:  v1
metadata: 
  name: mysql-pvc
  namespace: storage
spec: 
  accessModes: 
    - ReadWriteOnce       
  resources: 
    requests: 
      storage: 10Gi
  storageClassName: nfs-client  