apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: storage
  labels:
    name: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
    name: http
    nodePort: 30379
  selector:
    app: redis